# Generated by Django 3.0.6 on 2020-05-13 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='postitem',
            name='likes',
            field=models.IntegerField(default=0),
        ),
    ]
