# Generated by Django 3.0.6 on 2020-05-13 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_postitem_likes'),
    ]

    operations = [
        migrations.AddField(
            model_name='postitem',
            name='dislikes',
            field=models.IntegerField(default=0),
        ),
    ]
