# Generated by Django 3.0.6 on 2020-05-14 14:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_postitem_results'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postitem',
            name='dislikes',
        ),
        migrations.RemoveField(
            model_name='postitem',
            name='likes',
        ),
    ]
