# Generated by Django 3.0.6 on 2020-05-14 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0006_postitem_boast'),
    ]

    operations = [
        migrations.AddField(
            model_name='postitem',
            name='roast',
            field=models.BooleanField(default=False),
        ),
    ]
