# Generated by Django 3.0.6 on 2020-05-14 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0008_auto_20200514_1446'),
    ]

    operations = [
        migrations.RenameField(
            model_name='postitem',
            old_name='boast_or_roast',
            new_name='boast',
        ),
        migrations.AddField(
            model_name='postitem',
            name='roast',
            field=models.BooleanField(default=False),
        ),
    ]
