# Generated by Django 3.0.6 on 2020-05-14 15:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0010_auto_20200514_1505'),
    ]

    operations = [
        migrations.RenameField(
            model_name='postitem',
            old_name='boastorroast',
            new_name='boast_or_roast',
        ),
    ]
